SubjectiveTestSystem/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("user/", include("User.urls")),
    path("management/", include("Management.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path

from . import views

app_name = "User"

urlpatterns = [
    # ex: /user/login/
    path("login/", views.login, name="login"),
    # /user/logout/
    path("logout/", views.logout, name="logout"),
    # ex: /user/test/
    path("test/", views.index, name="index"),
    # ex: /user/test/5/
    path("test/<int:subjective_test_id>", views.view, name="view"),
    # ex: /user/test/delete/5/
    path("test/delete/<int:subjective_test_id>", views.delete, name="delete"),
]

Management/models.py
from django.db import models

# Create your models here.


class SubjectiveTest(models.Model):
    name = models.CharField(max_length=300)
    enable = models.BooleanField(help_text='Whether this test are enabled')
    def __str__(self):
        return self.name


class Question(models.Model):
    subjective_test = models.ForeignKey(SubjectiveTest, on_delete=models.CASCADE)
    type = models.IntegerField(
        help_text="Type of question. 0 is ABX, 1 is MOS, 2 is CMOS."
    )
    text = models.CharField(max_length=10240, help_text="Description.", default="")

    @staticmethod
    def question_type_to_str(type):
        if type == 0:
            return "ABX"
        if type == 1:
            return "MOS"
        if type == 2:
            return "CMOS"

    @staticmethod
    def str_to_question_type(s):
        if s == "ABX":
            return 0
        if s == "MOS":
            return 1
        if s == "CMOS":
            return 2
    
    def get_current_question_type_str(self):
        return self.question_type_to_str(self.type)

    def __str__(self):
        return "{}:{}".format(Question.question_type_to_str(self.type), self.text)


class Sample(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    file = models.FileField(max_length=4096)
    type = models.IntegerField(
        help_text="Type of sample. 0 is ground truth, 1 is predicted sample."
    )
    file_type = models.IntegerField(
        help_text="File type of sample. 0 is audio, 1 is video."
    )
    score = models.BooleanField(help_text="Whether this sample is scored.", default=0)
    text = models.CharField(max_length=10240, help_text="Description.", default="")
    original_name = models.CharField(max_length=4096,help_text='Original filename.',default='')

    @staticmethod
    def sample_type_to_str(type):
        if type == 1:
            return "Predicted"
        if type == 0:
            return "Ground Truth"

    @staticmethod
    def str_to_sample_type(s):
        if s == "P":
            return 1
        if s == "G":
            return 0

    @staticmethod
    def str_to_sample_file_type(s):
        if s =='audio':
            return 0
        if s =='video':
            return 1

    def get_current_sample_type_str(self):
        return self.sample_type_to_str(self.type)

User/models.py
from django.db import models
from Management.models import Sample, Question, SubjectiveTest
from django.contrib.auth.models import User

# Create your models here.


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sample_id = models.PositiveIntegerField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    subjective_test = models.ForeignKey(SubjectiveTest, on_delete=models.CASCADE)
    answer = models.IntegerField()

User/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label='Username',max_length=4096,required=True)

User/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import LoginForm
from django.contrib.auth import (
    authenticate,
    login as system_login,
    logout as system_logout,
)
from django.http import HttpResponseRedirect
from django.urls import reverse
from Management.models import SubjectiveTest, Question, Sample
from .models import Answer
from django.db import transaction

# Create your views here.

login_url = "/user/login"

DEFAULT_PASSWORD = "1234567890"


def login(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            login_form = LoginForm(request.POST)
            if login_form.is_valid():
                username = login_form.cleaned_data["username"]
                user = authenticate(
                    request, username=username, password=DEFAULT_PASSWORD
                )
                if user is not None:
                    system_login(request, user)
                else:
                    new_user = User.objects.create_user(
                        username, "test@test.com", DEFAULT_PASSWORD
                    )
                    new_user.save()
                    user = authenticate(
                        request, username=username, password=DEFAULT_PASSWORD
                    )
                    system_login(request, user)
        else:
            login_form = LoginForm()
            return render(request, "User/login.html", {"form": login_form})
    return HttpResponseRedirect(reverse("User:index"))


@login_required(login_url=login_url)
def index(request):
    all_tests = SubjectiveTest.objects.filter(enable__exact=True)
    return render(request, "User/index.html", context={"all_tests": all_tests})


@login_required(login_url=login_url)
def view(request, subjective_test_id):
    subjective_test = get_object_or_404(SubjectiveTest, pk=subjective_test_id)
    if request.method == "POST":
        # try:
        with transaction.atomic():
            for key in request.POST:
                temp = key.split("-")
                if len(temp) == 3:
                    _, question_id, sample_id = temp
                    try:
                        question = Question.objects.get(id=question_id)
                        sample = Sample.objects.get(id=sample_id)
                        answer = Answer.objects.get(
                            user=request.user,
                            subjective_test_id__exact=subjective_test_id,
                            question_id__exact=question_id,
                            sample_id__exact=sample_id,
                        )
                    except Answer.DoesNotExist:
                        answer = Answer(
                            question_id=question_id,
                            sample_id=sample_id,
                            subjective_test_id=subjective_test_id,
                            user=request.user,
                        )
                    except (Sample.DoesNotExist, Question.DoesNotExist):
                        pass
                    answer.answer = request.POST[key]
                    answer.save()
                elif len(temp) == 2:
                    # abx: POST[key]是sample id
                    # mos: POST[key]是给定的sample的mos得分
                    # cmos: POST[key]是给定的sample的CMOS得分
                    _, question_id = temp
                    try:
                        question = Question.objects.get(id=question_id)
                        answer = Answer.objects.get(
                            user=request.user,
                            subjective_test_id__exact=subjective_test_id,
                            question_id__exact=question_id,
                            sample_id__exact=0,
                        )
                    except Answer.DoesNotExist:
                        answer = Answer(
                            question_id=question_id,
                            sample_id=0,
                            subjective_test_id=subjective_test_id,
                            user=request.user,
                        )
                    except (Sample.DoesNotExist, Question.DoesNotExist):
                        continue
                    answer.answer = request.POST[key]
                    answer.save()
                else:
                    continue
        # except:
        #    pass
    return render(
        request,
        "User/view.html",
        context={"subjective_test": subjective_test, "user": request.user},
    )


@login_required(login_url=login_url)
def delete(request, subjective_test_id):
    pass


def logout(request):
    system_logout(request)
    return HttpResponseRedirect(reverse("User:login"))

User/templates/User/index.html
{% extends "./template.html" %}
{% block content %}
<div class="card">
    <div class="card-body">
        <table class="table mt-5">
            <thead>
                <tr>
                    <th scope="col" style="width: 10%;">ID</th>
                    <th scope="col" style="width: 60%">Name</th>
                    <th scope="col" style="text-align: center;">Action</th>
                </tr>
            </thead>
            <tbody>
                {% if all_tests %}
                {% for test in all_tests %}
                    <tr>
                        <th scope="row">{{ test.id }}</th>
                        <td>{{ test.name }}</td>
                        <td style="text-align: center;">
                            <a href="{% url 'User:view' test.id %}"><button type="button"
                                    class="btn btn-primary">View</button></a>
                            <a href="{% url 'User:delete' test.id %}"><button type="button"
                                class="btn btn-danger">Delete</button></a>
                        </td>
                    </tr>
                {% endfor %}
                {% else %}
                    <h3>No test currently.</h3>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>





{% endblock %}

User/templates/User/login.html
{% extends "./template.html" %}
{% load bootstrap4 %}
{% block content %}
<form action="{% url 'User:login' %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Login
  </button>
  {% endbuttons %}
</form>
{% endblock %}

User/templates/User/template.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<body class="d-flex flex-column h-100">

    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'User:index' %}">Subjective Test System</a>
                <a style="color: white" href="{% url 'User:logout' %}"><button class="btn btn-light">Logout</button></a>
            </div>
        </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="flex-shrink-0 mt-3">
        <div class="container mt-5">
            {% block content %}{% endblock %}
        </div>
    </main>

    <footer class="footer mt-auto py-3 fixed-bottom bg-primary">
        <div class="container">
            <span class="text-white"></span>
        </div>
    </footer>


</body>

User/templates/User/view.html
{% extends "./template.html" %}

{% block content %}
{% load ABX %}
{% load MOS %}
{% load CMOS %}
{% load shuffle %}
<form method='post' action="{% url 'User:view' subjective_test.id %}" class="form">
    {% csrf_token %}
    <div class="card m-5">
        {% for question in subjective_test.question_set.all %}
        {% if question.type == 0 %}
        <div class="card m-1">
            <div class="card-header">{{ question.get_current_question_type_str }} Question</div>
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted"></h6>
                <p class="card-text">{{ question.text }}</p>
                <ul class="list-group list-group-flush">
                    {% for sample in question.sample_set.all %}
                    <li class="list-group-item">
                        <p class="mb-0">{{ sample.text }}</p>
                        <div>
                            {{ sample.id }}
                            {% if sample.file_type %}
                            <video src="{{ sample.file.url }}" controls="controls" preload="none">Your browser doesn't support
                                video!</video>
                            {% else %}
                            <audio src="{{ sample.file.url }}" controls="controls" preload="none">Your browser doesn't support
                                audio!</audio>
                            {% endif %}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
                <div>
                    {% for sample in question.sample_set.all %}
                    {% if sample.score %}
                    <label>
                        <input type='radio' name="{{ question.get_current_question_type_str }}-{{ question.id }}"
                            value="{{ sample.id }}" required {% is_ABX_answer user subjective_test question sample.id as label %} {% if label %}checked{% endif %}>
                        {{ sample.id }}
                    </label>
                    {% endif %}
                    {% endfor %}
                    <label>
                        <input type='radio' name="{{ question.get_current_question_type_str }}-{{ question.id }}"
                            value="0" required {% is_ABX_answer user subjective_test question 0 as label %} {% if label %}checked{% endif %}>
                        NP
                    </label>
                </div>

            </div>
        </div>
        {% elif question.type == 1%}
        <div class="card m-1">
            <div class="card-header">{{ question.get_current_question_type_str }} Question</div>
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted"></h6>
                <p class="card-text">{{ question.text }}</p>
                <ul class="list-group list-group-flush">
                    {% for sample in question.sample_set.all|shuffle %}
                    <li class="list-group-item">
                        {% if sample.file_type %}
                        <video src="{{ sample.file.url }}" controls="controls" preload="none">Your browser doesn't support
                            video!</video>
                        {% else %}
                        <audio src="{{ sample.file.url }}" controls="controls" preload="none">Your browser doesn't support
                            audio!</audio>
                        {% endif %}
                        <p class="mb-0">{{ sample.text }}</p>
                        <div>
                            {% if sample.score %}
                            <label>
                                <input type='radio'
                                    name="{{ question.get_current_question_type_str }}-{{ question.id }}-{{ sample.id }}"
                                    value="1" required {% is_MOS_answer user subjective_test question sample 1 as label %}{% if label %}checked{% endif %}>
                                1
                            </label>
                            <label>
                                <input type='radio'
                                    name="{{ question.get_current_question_type_str }}-{{ question.id }}-{{ sample.id }}"
                                    value="2" required {% is_MOS_answer user subjective_test question sample 2 as label %}{% if label %}checked{% endif %}>
                                2
                            </label>
                            <label>
                                <input type='radio'
                                    name="{{ question.get_current_question_type_str }}-{{ question.id }}-{{ sample.id }}"
                                    value="3" required {% is_MOS_answer user subjective_test question sample 3 as label %}{% if label %}checked{% endif %}>
                                3
                            </label>
                            <label>
                                <input type='radio'
                                    name="{{ question.get_current_question_type_str }}-{{ question.id }}-{{ sample.id }}"
                                    value="4" required {% is_MOS_answer user subjective_test question sample 4 as label %}{% if label %}checked{% endif %}>
                                4
                            </label>
                            <label>
                                <input type='radio'
                                    name="{{ question.get_current_question_type_str }}-{{ question.id }}-{{ sample.id }}"
                                    value="5" required {% is_MOS_answer user subjective_test question sample 5 as label %}{% if label %}checked{% endif %}>
                                5
                            </label>
                            {% endif %}
                        </div>
                    </li>

                    {% endfor %}
                </ul>
            </div>
        </div>
        {% elif question.type == 2%}
        <div class="card m-1">
            <div class="card-header">{{ question.get_current_question_type_str }} Question</div>
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted"></h6>
                <p class="card-text">{{ question.text }}</p>
                <ul class="list-group list-group-flush">
                    {% for sample in question.sample_set.all|shuffle %}
                    <li class="list-group-item">
                        <p class="mb-0">{{ sample.text }}</p>
                        <div>
                            {{ sample.id }}
                            {% if sample.file_type %}
                            <video src="{{ sample.file.url }}" controls="controls" preload="none">Your browser doesn't support
                                video!</video>
                            {% else %}
                            <audio src="{{ sample.file.url }}" controls="controls" preload="none">Your browser doesn't support
                                audio!</audio>
                            {% endif %} 
                            <div>
                                {% if sample.score %}
                                <label>
                                    <input type='radio' name="{{ question.get_current_question_type_str }}-{{ question.id  }}-{{ sample.id }}" value="-3"
                                        required {% is_CMOS_answer user subjective_test question sample -3 as label %}{% if label %}checked{% endif %}>
                                    -3
                                </label>
                                <label>
                                    <input type='radio' name="{{ question.get_current_question_type_str }}-{{ question.id  }}-{{ sample.id }}" value="-2"
                                        required {% is_CMOS_answer user subjective_test question sample -2 as label %}{% if label %}checked{% endif %}>
                                    -2
                                </label>
                                <label>
                                    <input type='radio' name="{{ question.get_current_question_type_str }}-{{ question.id  }}-{{ sample.id }}" value="-1"
                                        required {% is_CMOS_answer user subjective_test question sample -1 as label %}{% if label %}checked{% endif %}>
                                    -1
                                </label>
                                <label>
                                    <input type='radio' name="{{ question.get_current_question_type_str }}-{{ question.id  }}-{{ sample.id }}" value="0"
                                        required {% is_CMOS_answer user subjective_test question sample 0 as label %}{% if label %}checked{% endif %}>
                                    0
                                </label>
                                <label>
                                    <input type='radio' name="{{ question.get_current_question_type_str }}-{{ question.id  }}-{{ sample.id }}" value="1"
                                        required {% is_CMOS_answer user subjective_test question sample 1 as label %}{% if label %}checked{% endif %}>
                                    1
                                </label>
                                <label>
                                    <input type='radio' name="{{ question.get_current_question_type_str }}-{{ question.id  }}-{{ sample.id }}" value="2"
                                        required {% is_CMOS_answer user subjective_test question sample 2 as label %}{% if label %}checked{% endif %}>
                                    2
                                </label>
                                <label>
                                    <input type='radio' name="{{ question.get_current_question_type_str }}-{{ question.id  }}-{{ sample.id }}" value="3"
                                        required {% is_CMOS_answer user subjective_test question sample 3 as label %}{% if label %}checked{% endif %}>
                                    3
                                </label>
                                {% endif %}
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>

            </div>
        </div>
        {% endif %}
        {% endfor %}
        <button type="submit" class="btn btn-success">Submit</button>
    </div>
</form>

{% endblock %}