Management/urls.py
from django.urls import path

from . import views

app_name = "Management"
urlpatterns = [
    # ex: /Management/login/
    path("login/", views.login, name="login"),
    # /Manegement/logout/
    path("logout/", views.logout, name="logout"),
    # ex: /Management/test/
    path("test/", views.index, name="index"),
    # ex: /Management/test/view/5
    path("test/view/<int:subjective_test_id>", views.view, name="view"),
    # ex: /Management/test/export/5
    path("test/export/<int:subjective_test_id>", views.export, name="export"),
    # ex: /Management/test/new/
    path("test/new/", views.new, name="new"),
    # ex: /Management/test/delete/5
    path("test/delete/<int:subjective_test_id>", views.delete, name="delete"),
    # /Management/test/enable/5
    path("test/enable/<int:subjective_test_id>", views.enable, name="enable"),
]

SubjectiveTestSystem/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path("user/", include("User.urls")),
    path("management/", include("Management.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path

from . import views

app_name = "User"

urlpatterns = [
    # ex: /user/login/
    path("login/", views.login, name="login"),
    # /user/logout/
    path("logout/", views.logout, name="logout"),
    # ex: /user/test/
    path("test/", views.index, name="index"),
    # ex: /user/test/5/
    path("test/<int:subjective_test_id>", views.view, name="view"),
    # ex: /user/test/delete/5/
    path("test/delete/<int:subjective_test_id>", views.delete, name="delete"),
]

Management/models.py
from django.db import models

# Create your models here.


class SubjectiveTest(models.Model):
    name = models.CharField(max_length=300)
    enable = models.BooleanField(help_text='Whether this test are enabled')
    def __str__(self):
        return self.name


class Question(models.Model):
    subjective_test = models.ForeignKey(SubjectiveTest, on_delete=models.CASCADE)
    type = models.IntegerField(
        help_text="Type of question. 0 is ABX, 1 is MOS, 2 is CMOS."
    )
    text = models.CharField(max_length=10240, help_text="Description.", default="")

    @staticmethod
    def question_type_to_str(type):
        if type == 0:
            return "ABX"
        if type == 1:
            return "MOS"
        if type == 2:
            return "CMOS"

    @staticmethod
    def str_to_question_type(s):
        if s == "ABX":
            return 0
        if s == "MOS":
            return 1
        if s == "CMOS":
            return 2
    
    def get_current_question_type_str(self):
        return self.question_type_to_str(self.type)

    def __str__(self):
        return "{}:{}".format(Question.question_type_to_str(self.type), self.text)


class Sample(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    file = models.FileField(max_length=4096)
    type = models.IntegerField(
        help_text="Type of sample. 0 is ground truth, 1 is predicted sample."
    )
    file_type = models.IntegerField(
        help_text="File type of sample. 0 is audio, 1 is video."
    )
    score = models.BooleanField(help_text="Whether this sample is scored.", default=0)
    text = models.CharField(max_length=10240, help_text="Description.", default="")
    original_name = models.CharField(max_length=4096,help_text='Original filename.',default='')

    @staticmethod
    def sample_type_to_str(type):
        if type == 1:
            return "Predicted"
        if type == 0:
            return "Ground Truth"

    @staticmethod
    def str_to_sample_type(s):
        if s == "P":
            return 1
        if s == "G":
            return 0

    @staticmethod
    def str_to_sample_file_type(s):
        if s =='audio':
            return 0
        if s =='video':
            return 1

    def get_current_sample_type_str(self):
        return self.sample_type_to_str(self.type)

Management/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label="Username", max_length=4096, required=True)
    password = forms.CharField(
        label="Password", max_length=4096, required=True, widget=forms.PasswordInput()
    )


class NewTestForm(forms.Form):
    name = forms.CharField(label="Test Name", max_length=4096, required=True)
    file = forms.FileField(allow_empty_file=False, required=True)

Management/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .forms import LoginForm, NewTestForm
from django.contrib.auth import (
    authenticate,
    login as system_login,
    logout as system_logout,
)
from .models import SubjectiveTest, Sample, Question
import zipfile
import uuid
import os
import json
from SubjectiveTestSystem.settings import MEDIA_ROOT
from django.core.files import File
from pathlib import Path
from django.db import transaction
import shutil
from User.models import Answer

# Create your views here.

login_url = "/management/login/"


def login(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            login_form = LoginForm(request.POST)
            if login_form.is_valid():
                password = login_form.cleaned_data["password"]
                username = login_form.cleaned_data["username"]
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    system_login(request, user)
                    return HttpResponseRedirect(reverse("Management:index"))
                else:
                    login_form.add_error("password", "Wrong password or username!")
        else:
            login_form = LoginForm()
        return render(request, "Management/login.html", {"form": login_form})
    return HttpResponseRedirect(reverse("Management:index"))


@login_required(login_url=login_url)
def index(request):
    all_tests = SubjectiveTest.objects.all()
    return render(request, "Management/index.html", context={"all_tests": all_tests})


@login_required(login_url=login_url)
def view(request, subjective_test_id):
    subjective_test = get_object_or_404(SubjectiveTest, pk=subjective_test_id)
    return render(
        request, "Management/view.html", context={"subjective_test": subjective_test}
    )


@login_required(login_url=login_url)
def export(request, subjective_test_id):
    subjective_test = get_object_or_404(SubjectiveTest, pk=subjective_test_id)
    # SubjectiveTest -> Question -> Sample -> User -> Answer
    # abx: answer.answer是sample id
    # mos: answer.answer是给定的sample的mos得分
    # cmos: answer.answer是给定的sample的CMOS得分
    response = []
    for question in subjective_test.question_set.all():
        type = question.get_current_question_type_str()
        q = {}
        if type== 'ABX':
            answers = Answer.objects.all().filter(subjective_test_id__exact=subjective_test_id,question_id__exact=question.id)
            q['type'] = 'ABX'
            q['ans'] = []
            for answer in answers:
                sample = Sample.objects.get(id__exact=answer.answer)
                q['ans'].append({'name':sample.original_name,'user':answer.user.username})
            response.append(q)
        elif type=='MOS':
            q['type'] = "MOS"
            q['ans'] = []
            for sample in question.sample_set.all():
                if sample.score:
                    answers = Answer.objects.all().filter(subjective_test_id__exact=subjective_test_id,question_id__exact=question.id,
                    sample_id__exact=sample.id)
                    qs = {'sample_name':sample.original_name,'ans':[]}
                    for answer in answers:
                        qs['ans'].append({'user':answer.user.username,'score':answer.answer})
                    q['ans'].append(qs)
            response.append(q)
        elif type=='CMOS':
            q['type'] = 'CMOS'
            q['ans'] = []
            for sample in question.sample_set.all():
                if sample.score:
                    answers = Answer.objects.all().filter(subjective_test_id__exact=subjective_test_id,question_id__exact=question.id,
                    sample_id__exact=sample.id)
                    qs = {'sample_name':sample.original_name,'ans':[]}
                    for answer in answers:
                        qs['ans'].append({'user':answer.user.username,'score':answer.answer})
                    q['ans'].append(qs)
            response.append(q)
    return JsonResponse(response,safe=False)


CONFIG_FILENAME = "config.json"


@login_required(login_url=login_url)
def new(request):
    if request.method == "POST":
        form = NewTestForm(request.POST, request.FILES)
        if form.is_valid:
            file = request.FILES["file"]
            destination_dir_name = uuid.uuid4().hex
            destination_dir_path = os.path.join(MEDIA_ROOT, destination_dir_name)
            destination_name = destination_dir_path + ".zip"
            with open(destination_name, "wb") as destination:
                for chunk in file.chunks():
                    destination.write(chunk)
            zip_file = zipfile.ZipFile(destination_name, "r", allowZip64=True)
            if CONFIG_FILENAME in zip_file.namelist():
                zip_file.extractall(destination_dir_path)
                zip_file.close()
                with open(os.path.join(destination_dir_path, CONFIG_FILENAME)) as f:
                    configuration_json = json.load(f)
                try:
                    with transaction.atomic():
                        subjective_test = SubjectiveTest(
                            name=request.POST["name"], enable=True
                        )
                        subjective_test.save()
                        for question_conf in configuration_json:
                            question = Question(
                                subjective_test=subjective_test,
                                type=Question.str_to_question_type(
                                    question_conf["type"]
                                ),
                                text=question_conf["text"],
                            )
                            question.save()
                            for sample_conf in question_conf["samples"]:
                                path = Path(
                                    os.path.join(
                                        destination_dir_path, sample_conf["path"]
                                    )
                                )
                                with path.open(mode="rb") as f:
                                    sample = Sample(
                                        question=question,
                                        type=Sample.str_to_sample_type(
                                            sample_conf["type"]
                                        ),
                                        file_type=Sample.str_to_sample_file_type(
                                            sample_conf["file_type"]
                                        ),
                                        score=sample_conf["score"],
                                        text=sample_conf["text"],
                                        file=File(f, name=path.name),
                                        original_name=path.name,
                                    )
                                    sample.save()
                except:
                    os.removedirs(destination_dir_path)
                    os.remove(destination_name)
                    form.add_error("file", "create new subjective test error!")
                else:
                    shutil.rmtree(destination_dir_path)
                    os.remove(destination_name)
                    return HttpResponseRedirect(reverse("Management:index"))
            else:
                form.add_error("file", f"can't find {CONFIG_FILENAME} in zip file!")

    else:
        form = NewTestForm()
    return render(request, "Management/new.html", context={"form": form})


@login_required(login_url=login_url)
def delete(request, subjective_test_id):
    SubjectiveTest.objects.filter(id=subjective_test_id).delete()
    return HttpResponseRedirect(reverse("Management:index"))


@login_required(login_url=login_url)
def enable(request, subjective_test_id):
    subjective_test = get_object_or_404(SubjectiveTest, pk=subjective_test_id)
    subjective_test.enable = not subjective_test.enable
    subjective_test.save()
    return HttpResponseRedirect(reverse("Management:index"))


def logout(request):
    system_logout(request)
    return HttpResponseRedirect(reverse("Management:login"))

Management/templates/Management/index.html
{% extends "./template.html" %}
{% block content %}
<div class="card m-5">
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" style="width: 10%;">ID</th>
                    <th scope="col" style="width: 50%">Name</th>
                    <th scope="col" style="text-align: center;">Action</th>
                </tr>
            </thead>
            <tbody>
                {% if all_tests %}
                {% for test in all_tests %}
                <tr>
                    <th scope="row">{{ test.id }}</th>
                    <td>{{ test.name }}</td>
                    <td style="text-align: center;">

                        <a href="{% url 'Management:enable' test.id %}">
                            {% if test.enable %}
                            <button type="button" class="btn btn-secondary">Stop</button>
                            {% else %}
                            <button type="button" class="btn btn-success">Start</button>
                            {% endif %}
                        </a>

                        <a href="{% url 'Management:view' test.id %}"><button type="button"
                                class="btn btn-primary">View</button></a>
                        <a href="{% url 'Management:export' test.id %}"><button type='button'
                                class='btn btn-primary'>Export</button></a>
                        <a href="{% url 'Management:delete' test.id %}"><button type="button"
                                class="btn btn-danger">Delete</button></a>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <h3>No test. Please add new test by uploading content.</h3>
                {% endif %}
                <tr>
                    <td colspan="3" style="text-align: center;">
                        <a href="{% url 'Management:new' %}" target="_blank">
                            <button type="button" class="btn btn-success">Add New Test</button>
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>





{% endblock %}

Management/templates/Management/login.html
{% extends "./template.html" %}
{% load bootstrap4 %}
{% block content %}
<form action="{% url 'Management:login' %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Login
  </button>
  {% endbuttons %}
</form>
{% endblock %}

Management/templates/Management/new.html
{% extends './template.html' %}
{% load bootstrap4 %}
{% block content %}
<form action="{% url 'Management:new' %}" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">
        Add
      </button>
    {% endbuttons %}
</form>
{% endblock %}

Management/templates/Management/template.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<body class="d-flex flex-column h-100">

    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'Management:index' %}">Admin Panel</a>
                <a style="color: white" href="{% url 'Management:logout' %}"><button class="btn btn-light">Logout</button></a>
            </div>
        </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="flex-shrink-0 mt-3">
        <div class="container mt-5">
            {% block content %}{% endblock %}
        </div>
    </main>

    <footer class="footer mt-auto py-3 fixed-bottom bg-primary">
        <div class="container">
            <span class="text-white"></span>
        </div>
    </footer>


</body>

Management/templates/Management/view.html
{% extends "./template.html" %}

{% block content %}
    <div class="m-5">
        {% for question in subjective_test.question_set.all %}
            <div class="card">
                <div class="card-header">{{ question.get_current_question_type_str }} Question</div>
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted"></h6>
                    <p class="card-text">{{ question.text }}</p>
                    <ul class="list-group list-group-flush">
                    {% for sample in question.sample_set.all %}
                        <li class="list-group-item">
                        {% if sample.file_type %}
                            <video src="{{ sample.file.url }}" controls="controls" preload="none">Your browser doesn't support video!</video>
                        {% else %}
                            <audio src="{{ sample.file.url }}" controls="controls" preload="none">Your browser doesn't support audio!</audio>
                        {% endif %}
                        <p class="mb-0">{{ sample.text }}</p>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}